config/routes.rb
Rails.application.routes.draw do
  root to: "flights#index"
  resources :flights, only: [ :index ]
  resources :bookings, only: [ :new, :create, :show ]
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: "departure_airport_id", class_name: "Flight"
  has_many :arriving_flights, foreign_key: "arrival_airport_id", class_name: "Flight"

  validates :iata, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  validates_associated :flight

  has_many :passengers, inverse_of: :booking, dependent: :destroy
  accepts_nested_attributes_for :passengers, allow_destroy: true

  validates :passengers, presence: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings

  def formatted_flight_date
    start.strftime("%Y-%m-%d")
  end

  def formatted_flight_time
    start.strftime("%I:%M %p")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates_associated :booking
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    redirect_to flights_path if !params[:flight_id].present?

    passengers = params[:passengers]

    # Redirect if the params Passengers does not exist or is not a integer string (eg. '1', '8', '13')
    if !passengers || !passengers.match?(/\A-?\d+\z/)
      redirect_to flights_path
    end

    passengers = passengers.to_i

    @booking = Booking.new
    passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer
          .with(passenger: passenger, flight: @booking.flight)
          .confirmation_email
          .deliver_later
      end
      redirect_to @booking, notice: "Booked flight success."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.expect(booking: [
      :flight_id,
      passengers_attributes: [ [ :id, :name, :email ] ]
    ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    filter_condition = {}

    if params[:departure_airport].present?
      filter_condition[:departure_airport_id] = params[:departure_airport]
    end

    if params[:arrival_airport].present?
      filter_condition[:arrival_airport_id] = params[:arrival_airport]
    end

    if params[:date].present?
      date = Date.parse(params[:date])

      filter_condition[:start] = (date.beginning_of_day)..(date.end_of_day)
    end

    @flights = Flight.where(filter_condition).includes(:departure_airport, :arrival_airport).order(start: :asc)

    @flight_dates = Flight.pluck(:start).map { |item| item.strftime("%Y-%m-%d") }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_flight_details.html.erb
<ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <article class="ms-2 me-auto">
      <h3 class="text-secondary fs-6">Departure Airport</h3>
      <p class="fs-3 font-monospace"><%= flight.departure_airport.iata %></p>
    </article>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <article class="ms-2 me-auto">
      <h3 class="text-secondary fs-6">Arrival Airport</h3>
      <p class="fs-3 font-monospace"><%= flight.arrival_airport.iata %></p>
    </article>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <article class="ms-2 me-auto">
      <h3 class="text-secondary fs-6">Take off at</h3>
      <time class="fs-4 font-monospace" datetime="<%= flight.start %>">
        <%= "#{flight.formatted_flight_date}   #{flight.formatted_flight_time}" %>
      </time>
    </article>
  </li>
</ul>

app/views/bookings/_form.html.erb
<%= form_with model: @booking do |f| %>
  <%= f.hidden_field :flight_id, value: params[:flight_id] %>
  <div class="vstack gap-4">
    <%= f.fields_for :passengers do |passengers_form| %>
      <div class="border p-3 rounded-2">
        <p class="font-monospace text-secondary fs-6 fw-lighter">Passenger <%= passengers_form.index + 1 %></p>
        <div class="vstack gap-2">
          <div>
            <%= passengers_form.label :name, class: "form-label" %>
            <%= passengers_form.text_field :name, class: "form-control #{'is-invalid' if passengers_form.object.errors[:name].any?}", autofocus: passengers_form.index == 0 %>
          </div>
          <div>
            <%= passengers_form.label :email, class: "form-label" %>
            <%= passengers_form.email_field :email, class: "form-control #{'is-invalid' if passengers_form.object.errors[:name].any?}" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mt-4 hstack gap-3">
    <%= f.submit "Complete Booking", class: "btn btn-primary"  %>
    <%= link_to "Cancel", flights_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/bookings/_passengers_table.html.erb
<table class="table table-responsive">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <% passengers.each_with_index do |passenger, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= passenger.name %></td>
        <td><%= passenger.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<section>
  <h1 class="mb-5">Book the flight</h1>
  <div>
    <%= render "form" %>
  </div>
</section>

app/views/bookings/show.html.erb
<h1>Bookings Details</h1>
<section class="my-5">
  <h2 class="lead">Flight Information</h2>
  <%= render "flight_details", flight: @booking.flight %>
</section>
<section class="my-5">
  <h2 class="lead">Passengers</h2>
  <div class="border rounded-2 p-3">
    <%= render "passengers_table", passengers: @booking.passengers %>
  </div>
</section>

app/views/flights/_flights_filter.html.erb
<div>
  <%= form_with url: flights_path, method: :get do |f| %>
    <div class="row g-3">
      <div class="col-12 col-sm-6 col-lg-3">
        <%= f.label :departure_airport, class: "form-label" %>
        <%= f.collection_select :departure_airport, Airport.order(:iata), :id, :iata, { prompt: "Any", selected: params[:departure_airport] }, { class: "form-select" }  %>
      </div>
      <div class="col-12 col-sm-6 col-lg-3">
        <%= f.label :arrival_airport, class: "form-label" %>
        <%= f.collection_select :arrival_airport, Airport.order(:iata), :id, :iata, { prompt: "Any", selected: params[:arrival_airport] }, { class: "form-select" } %>
      </div>
      <div class="col-12 col-sm-6 col-lg-3">
        <%= f.label :passengers, class: "form-label" %>
        <%= f.select :passengers, 1..4, { selected: params[:passengers] || 1 }, { class: "form-select"} %>
      </div>
      <div class="col-12 col-sm-6 col-lg-3">
        <%= f.label :date, class: "form-label" %>
        <%= f.select :date, flight_dates, { prompt: "Select Date", selected: params[:date] }, { class: "form-select" } %>
      </div>
    </div>
    <div class="mt-4 hstack gap-2">
      <%= f.submit "Apply Filters", class: "btn btn-primary" %>
      <%= link_to "Clear Filters", flights_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/flights/_flights_table.html.erb
<table class="table table-responsive table-striped table-bordered text-center">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Departure Airport</th>
      <th scope="col">Arrival Airport</th>
      <th scope="col">Date</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% flights.each do |flight| %>
      <tr>
        <th scope="row"><%= flight.id %></th>
        <td class="font-monospace"><%= flight.departure_airport.iata %></td>
        <td class="font-monospace"><%= flight.arrival_airport.iata %></td>
        <td><%= flight.formatted_flight_date %></td>
        <td>
          <%= link_to "Book", new_booking_path(flight_id: flight.id, passengers: params[:passengers] || 1), class: "btn btn-outline-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/index.html.erb
<section class="mb-5">
  <div class="border p-4 rounded-2">
    <h2 class="mb-4">Filter Flights</h2>
    <%= render "flights_filter", flight_dates: @flight_dates %>
  </div>
</section>
<section>
  <h1>Available Flights (<%= @flights.length %>)</h1>
  <div class="mt-4">
    <%= render "flights_table", flights: @flights %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render "shared/alerts" %>
    <main class="container py-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="container my-5">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="container my-5">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>